### ISSUE TITLE
It do not support chinese charaters!

### ISSUE THREAD

**Issue by acekingke** [quinton-ashley/p5play#248]
I use the sparite 
```
Sprite.text =  "中国";
```
It shows  somethings like this:
<img width="50" alt="image" src="https://github.com/quinton-ashley/p5play/assets/7586502/06f52b62-1b57-4731-bdc7-ed969160d871">

**Comment by quinton-ashley** [comment]
q5.js and p5.js both support Chinese text by default, so p5play will support Chinese text. You can not name a sprite `Sprite` with a capital letter though, since Sprite is the name of the class. Also if you load another font make sure that font supports Chinese texts.

<img width="254" alt="Screenshot 2023-05-26 at 09 51 10" src="https://github.com/quinton-ashley/p5play/assets/20031683/7652b9d2-18db-4eef-a495-ea2327999409">

**Comment by acekingke** [comment]
Thank you very much. I will try it again.

Quinton Ashley ***@***.***> 于2023年5月26日周五 22:53写道：
