### ISSUE TITLE
Make colliders based on text shapes

### ISSUE THREAD

**Issue by dhowe** [quinton-ashley/p5play#268]
Very cool that you've added box2d with p5play. A couple of quick question about the type of bounding boxes (colliders?) supported for sprites with text, from easy to hard (not sure if I'm using the correct terminology here):

* How to disable visibility for the rectangle bounding box/collider on a sprite with text (so only the text is seen)? 
* Is there an easy way to use the bounds of the text as the collider for the text-sprite, rather than setting width/height etc. manually?
* And if so, will the text use the bounds for the font, or the sometimes tighter bounds for the string (for example, if there are no ascenders or descenders in the string).
* And finally is it possible to use the glyph outlines as the collider, rather than a rectangle, and if so, how are interior holes handled (eg, the space at the center of an "O" or a "A")?

**Comment by quinton-ashley** [comment]
To answer your first question, you could make a custom draw function for the sprite and draw its text there. `text(sprite.text)`
https://p5play.org/learn/sprite.html?page=14

I've actually had a card for this idea on the project planning page for a while because I think it'd be really cool!
https://github.com/quinton-ashley/p5play/projects/1

It'd probably be best for it to be an add-on for p5play, since it would be a niche feature. I'm stuck doing bug fixes right now haha but if you wanted to try it here's what you'd need to do:

- turn the text into arrays of vertexes, this could maybe be done by converting the text to svg but then you'd need to plot points along curves, it could also be done through edge detection on an image of the text

- create chain colliders from the vertex lists, since the glyphs are concave they'd be chain colliders, though it'd be nice to have an algorithm in p5play for making concave polygons out of multiple convex polygons
https://p5play.org/learn/sprite.html?page=11
https://p5play.org/learn/sprite.html?page=12

**Comment by dhowe** [comment]
I'd implemented this once before with opentype and box2d, but its been a while. There are a lot of tricky edge cases with things like inner-holes and punctuation. And, as far as I know, it would only work with ttf/otf fonts (I don't think there's a way to get this data easily from css fonts)

I guess the first step would be to auto-create a rectangular collider for a given font/size, based on its bounds (either normal or tight) ... perhaps this could be an option on the sprite, `sprite.useTextBounds` or similar

**Comment by quinton-ashley** [comment]
Ah I forgot to answer that part. You can basically do that already by using `createTextImage` then assign the image to the sprite, it will inherit the image's size or you can also explicitly define that.

**Comment by quinton-ashley** [comment]
Yeah I bet it could get tricky! You did it for c++ box2d?

**Comment by dhowe** [comment]
js

**Comment by quinton-ashley** [comment]
ah shouldn't be too hard to port it to p5play then. Did your code make a list of vertexes for each letter?

**Comment by dhowe** [comment]
letters often contain multiple polygon shapes, each of which is constructed from an ordered list of vertices

**Comment by dhowe** [comment]
info for contributors, instructions on building the lib ?

**Comment by quinton-ashley** [comment]
@dhowe check out the p5play-web repo readme.md
